syntax on
set nocompatible
set hidden
filetype plugin indent on
set backspace=indent,eol,start
set cursorline
set noswapfile
set number

" Theme
" TODO get 24 bit color in tmux + iterm
" https://deductivelabs.com/en/2016/03/using-true-color-vim-tmux/
" https://www.reddit.com/r/vim/comments/2ozwe4/24_bit_vim_in_osx_iterm2_a_reality/
" set guicolors
" set background=dark
" colorscheme boa


filetype off
let &runtimepath.=',~/.vim/bundle/ale'
filetype plugin on

" Plugins
call plug#begin('~/.vim/plugged')
  Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
  Plug 'tpope/vim-fugitive'
  Plug 'tpope/vim-rhubarb'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-eunuch'
  Plug 'airblade/vim-gitgutter'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'kchmck/vim-coffee-script'
  Plug 'vim-syntastic/syntastic'
  Plug 'roman/golden-ratio'
  Plug 'vim-ctrlspace/vim-ctrlspace'
  Plug 'christoomey/vim-tmux-navigator'
  Plug 'w0rp/ale'
  Plug 'scrooloose/nerdcommenter'
call plug#end()

" Ctrl + P
set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:CtrlSpaceSymbols = { "File": "◯", "CTab": "▣", "Tabs": "▢" }

" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_left_sep=''
let g:airline_right_sep=''

" Shortcuts
source ~/.vim/alias

" Plugins
source ~/.vim/plugins

" ctrlp ignore
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'

" Dictionary
set dictionary=/usr/share/dict/words

" Session Management
" ...?

" Indentation
" keep selection when reindenting
set expandtab ts=2 shiftwidth=2 softtabstop=2
vnoremap > >gv
vnoremap < <gv


" Highlight curr line (only active window)
augroup CursorLine
	au!
	au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
	au WinLeave * setlocal nocursorline
augroup END


set mouse=a
if has("mouse_sgr") && !has('nvim')
	set ttyfast
	set ttymouse=sgr
endif

set autoread


