syntax on
set nocompatible
set hidden
filetype plugin indent on
set backspace=indent,eol,start
set cursorline
set noswapfile
set number
set encoding=utf-8
set t_Co=256
set wildmenu
set lazyredraw

" Wildignore
set wildignore+=.DS_Store
set wildignore+=*.jpg,*.jpeg,*.gif,*.png,*.gif,*.psd,*.o,*.obj,*.min.js
set wildignore+=*/bower_components/*,*/node_modules/*
set wildignore+=*/smarty/*,*/vendor/*,*/.git/*,*/.hg/*,*/.svn/*,*/.sass-cache/*,*/log/*,*/tmp/*,*/build/*,*/ckeditor/*,*/doc/*,*/source_maps/*,*/dist/*

" Share OSX's clipboard
set clipboard=unnamed

" Theme
set t_Co=256
set background=dark


filetype off
let &runtimepath.=',~/.vim/bundle/ale'
filetype plugin on

" Dictionary
set dictionary=/usr/share/dict/words

" Session Management
" ...?

" Indentation
filetype plugin indent on
set expandtab ts=2 shiftwidth=2 softtabstop=2

" Highlight curr line (only active window)
augroup CursorLine
  au!
  au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
  au WinLeave * setlocal nocursorline
augroup END


set mouse=a
if has("mouse_sgr") && !has('nvim')
  set ttyfast
  set ttymouse=sgr
endif

set autoread
set autowrite

" Search
set incsearch

" Imports
source ~/.vim/plugins.vim
source ~/.vim/alias.vim

" Theme
 colorscheme Tomorrow-Night-Eighties
let g:airline_theme='base16_eighties'
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" Grey line numbers
highlight LineNr ctermfg=grey

set omnifunc=syntaxcomplete#Complete
autocmd BufEnter * EnableStripWhitespaceOnSave

" Use Deoplete
let g:deoplete#enable_at_startup = 1
