# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh
export DOTFILES=~/Projects/dotfiles

# PyEnv stuff
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="$HOME/.yarn/bin:$PATH"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# ZSH_THEME="agnoster"
ZSH_THEME="avit"
DEV_ALLOW_ITERM2_INTEGRATION=1
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git/*'"

# Plugins
# (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(
  git
  colored-man
  colorize
  github
  virtualenv
  brew
  osx
  z
  zsh-syntax-highlighting
  zsh-completions
  fzf-zsh
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh
source $DOTFILES/zsh/aliases.zsh
source $DOTFILES/zsh/functions.zsh

# Shopify's dev resource
source /opt/dev/dev.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ctrl+z in zsh types fg then hits enter to jump back to the last job.
bindkey -s '^z' "fg\n"

bindkey -v
export KEYTIMEOUT=1

eval "$(pyenv init -)"
