# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export DOTFILES=~/Projects/dotfiles

# zsh plugin manager
source /usr/local/share/antigen/antigen.zsh
antigen bundle git
antigen bundle pip
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen apply

# Enable auto-completion
autoload -Uz compinit
compinit

source $DOTFILES/zsh/variables.zsh
source $DOTFILES/zsh/paths.zsh
source $DOTFILES/zsh/nvm.zsh
source $DOTFILES/zsh/ui.zsh

source "$ZSH/oh-my-zsh.sh"

source $DOTFILES/zsh/aliases.zsh
source $DOTFILES/zsh/tools.zsh

# Vi mode for zsh input
bindkey -v
export KEYTIMEOUT=1
# Backspace over insert start point
bindkey "^?" backward-delete-char


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
if [ -e /Users/cmarlow/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/cmarlow/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
